query GetMyProfile @auth(level: USER, insecureReason: "This query fetches the current user's profile and uses auth.uid for security.") {
  user(key: {id_expr: "auth.uid"}) {
    id
    displayName
    email
    goal
    height
    weight
    photoUrl
    createdAt
  }
}

mutation CreateExercise($name: String!, $description: String, $instructions: String, $muscleGroup: String) @auth(level: USER, insecureReason: "This mutation allows logged-in users to create new exercises.") {
  exercise_insert(data: {
    name: $name,
    description: $description,
    instructions: $instructions,
    muscleGroup: $muscleGroup,
    createdAt_expr: "request.time"
  })
}

query ListPublicWorkoutRoutines @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  workoutRoutines(where: {public: {eq: true}}) {
    id
    name
    description
    user {
      displayName
    }
    createdAt
  }
}

mutation LogWorkoutSession($workoutDate: Date!, $workoutRoutineId: UUID, $notes: String) @auth(level: USER, insecureReason: "This mutation allows logged-in users to log their workout sessions and uses auth.uid for security.") {
  workoutSession_insert(data: {
    userId_expr: "auth.uid",
    workoutDate: $workoutDate,
    workoutRoutineId: $workoutRoutineId,
    notes: $notes,
    createdAt_expr: "request.time"
  })
}